name: Run tests

on:
  workflow_call:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ${{ vars.RUNNER_TYPE }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch_name }}
      
      - name: Run tests in docker container
        run: |
          docker build -t cesr-verifier .
          docker run -i --rm --entrypoint "/bin/bash" cesr-verifier -c "pip install pytest && python -m pytest tests/"
